/*
 * ADC.c
 *
 * Created: 3/15/2021 3:10:31 PM
 *  Author: VAIO
 */ 
#include "ADC.h"


void ADC_Init(Uint8t channel){
	/*choose voltage source -AVCC*/
	CLR_BIT(ADMUX,REFS1);
	SET_BIT(ADMUX,REFS0);
	
	/*choose REIGHT ADJUST*/
	CLR_BIT(ADMUX,ADLAR);
	
	/*choose channel*/
	
	switch(channel){
		
		case ADC0:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);CLR_BIT(ADMUX,MUX2);CLR_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX0);
		case ADC1:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);CLR_BIT(ADMUX,MUX2);CLR_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX0);
		case ADC2:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);CLR_BIT(ADMUX,MUX2);SET_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX0);
		case ADC3:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);CLR_BIT(ADMUX,MUX2);SET_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX0);
		case ADC4:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);SET_BIT(ADMUX,MUX2);CLR_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX0);
		case ADC5:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);SET_BIT(ADMUX,MUX2);CLR_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX0);
		case ADC6:
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);SET_BIT(ADMUX,MUX2);SET_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX4);CLR_BIT(ADMUX,MUX3);SET_BIT(ADMUX,MUX2);SET_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX0);
		break;
	}
		/*USE AUTO TRIGGER MODE*/
		SET_BIT(ADCSRA,ADATE);
		/*ADC ENABLE*/
		SET_BIT(ADCSRA,ADEN);
		/*CHOOSE PRESCALER*/
		SET_BIT(ADCSRA,ADPS2);SET_BIT(ADCSRA,ADPS1);SET_BIT(ADCSRA,ADPS0);
		
		
		
	
}
Uint16t ADC_Read(void){
	Uint16t var=0;
	/*start of conversion signal - SOC*/
	SET_BIT(ADCSRA,ADSC);
	/*wait till flag is set automatically * END OF CONVERSION EOF*/
	while (GET_BIT(ADCSRA,ADIF)!=1); /*polling mode*/
	var=ADC;
	return var;
	
	
	
	
}