/*
 * KEYPAD_CONFIG.h
 *
 * Created: 2/24/2021 4:26:12 PM
 *  Author: VAIO
 */ 


#ifndef KEYPAD_CONFIG_H_
#define KEYPAD_CONFIG_H_

/*MACROS*/
#include "CPU_CONFIGURATION.h"


/*KEYPAD PORT NEEDED*/
#define KEYPAD_PORT DIO_PORTD
/*KEYPAD OUTPUT PINS*/
#define KEYPAD_OUT_PIN0		DIO_PIN0
#define KEYPAD_OUT_PIN1		DIO_PIN1
#define KEYPAD_OUT_PIN2		DIO_PIN2
#define KEYPAD_OUT_PIN3		DIO_PIN3
/*KEYPAD INPUT PINS*/
#define KEYPAD_INP_PIN0		DIO_PIN4
#define KEYPAD_INP_PIN1		DIO_PIN5
#define KEYPAD_INP_PIN2		DIO_PIN6
#define KEYPAD_INP_PIN3		DIO_PIN7

/*KEYPAD STATES*/
#define KEYPAD_INPUT		DIO_PIN_INPUT
#define KEYPAD_OUTPUT		DIO_PIN_OUTPUT
#define KEYPAD_HIGH			DIO_PIN_HIGH
#define KEYPAD_LOW			DIO_PIN_LOW

/* START AND END OF COLOMN PINS*/
#define COL_INIT			0
#define COL_FINAL			3

/*START AND END OF ROW PINS*/
#define	ROW_INIT			4
#define ROW_FINAL			7

#endif /* KEYPAD_CONFIG_H_ */