/*
 * LCD_CONFIG.h
 *
 * Created: 2/23/2021 5:16:40 PM
 *  Author: VAIO
 */ 


#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_
/*
WHAT SHOULD I DO HERE:
1- MACROS NEEDED
2-RENAMING OF PORTS NEEDE
3-RENAMING OF PINS NEEDED
4-STATES
*/
#include "CPU_CONFIGURATION.h"
/* LCD MODE*/
#define LCD_MODE		 4
/* LCD CMD PORT*/
#define LCD_CMD_PORT	DIO_PORTB
/*LCD DATA PORT*/
#define LCD_DATA_PORT	DIO_PORTA
/* CONTROL PINS*/
#define LCD_RS			DIO_PIN1
#define LCD_RW			DIO_PIN2
#define LCD_EN			DIO_PIN3
/* DATA PINS */
#define LCD_D4			DIO_PIN4
#define LCD_D5			DIO_PIN5
#define LCD_D6			DIO_PIN6
#define LCD_D7			DIO_PIN7
/*STATES*/
#define LCD_OUTPUT	DIO_PIN_OUTPUT
#define LCD_LOW		DIO_PIN_LOW
#define LCD_HIGH	DIO_PIN_HIGH



#endif /* LCD_CONFIG_H_ */