/*
 * SEV_SEG.c
 *
 * Created: 2/22/2021 2:26:00 PM
 *  Author: VAIO
 */ 

#include "SEV_SEG.h"

void SEVSEG_Init(void)						 /*INITIALIZATION FUNCTION OF MODULE TO DEFINE PIN DIRECTION*/
{
	/*COMMAND PORTS PINS*/
	DIO_SetPin_Direction(SEVSEG_CMD_PORT,SEVSEG_EN1,SEVSEG_OUTPUT);
	DIO_SetPin_Direction(SEVSEG_CMD_PORT,SEVSEG_EN2,SEVSEG_OUTPUT);
	/*DATA PORTS PINS*/
	DIO_SetPin_Direction(SEVSEG_DTA_PORT,SEVSEG_DTA0_A,SEVSEG_OUTPUT);
	DIO_SetPin_Direction(SEVSEG_DTA_PORT,SEVSEG_DTA1_B,SEVSEG_OUTPUT);
	DIO_SetPin_Direction(SEVSEG_DTA_PORT,SEVSEG_DTA2_C,SEVSEG_OUTPUT);
	DIO_SetPin_Direction(SEVSEG_DTA_PORT,SEVSEG_DTA3_D,SEVSEG_OUTPUT);
	
}
void SEVSEG_ENB1(void)							 /*ENABLE FIRST SEVEN SEGMENT*/
{
	DIO_SetPin_Value(SEVSEG_CMD_PORT,SEVSEG_EN1,SEVSEG_HIGH);
	
}
void SEVSEG_DIS1(void)							 /*DISABLE FIRST SEVEN SEGMENT*/
{
	DIO_SetPin_Value(SEVSEG_CMD_PORT,SEVSEG_EN1,SEVSEG_LOW);
	
}
void SEVSEG_ENB2(void)						/*ENABLE SECOND SEVEN SEGMENT*/
{
	DIO_SetPin_Value(SEVSEG_CMD_PORT,SEVSEG_EN2,SEVSEG_HIGH);
	
}
void SEVSEG_DIS2(void)							/*DISABLE SECOND SEVEN SEGMENT*/
{
	DIO_SetPin_Value(SEVSEG_CMD_PORT,SEVSEG_EN2,SEVSEG_LOW);
	
}
void SEVSEG_DISPLAY(Uint8t data)					    /* DISPLAY VALUE FROM 0 TO 99 */
{
	int data0=data % 10;
	int data1=data/10;
	SEVSEG_ENB1();
	SEVSEG_DIS2();
	PORTA = (data0 << 4) | (PORTA & 0X0F);
	_delay_ms(125);
	
	SEVSEG_DIS1();
	SEVSEG_ENB2();
	PORTA = (data1 << 4) | (PORTA & 0X0F);
	_delay_ms(125);
}